import React from 'react';
import { Table } from 'antd';
import type { ColumnsType } from 'antd/es/table';

interface DataType {
  key: React.ReactNode;
  param: string;
  name: number | string;
  required?: 'Y' | 'N';
  type?: string;
  length?: number;
  demo?: string;
  describe: string;
  children?: DataType[];
}

const columns: ColumnsType<DataType> = [
  {
    title: '参数',
    dataIndex: 'param',
    width: 297,
    key: 'param',
  },
  {
    title: '名称',
    dataIndex: 'name',
    key: 'name',
  },
  {
    title: '是否必填',
    dataIndex: 'required',
    key: 'required',
  },
  {
    title: '类型',
    dataIndex: 'type',
    key: 'type',
  },
  {
    title: '长度',
    dataIndex: 'length',
    key: 'length',
  },
  {
    title: '示例',
    dataIndex: 'demo',
    key: 'demo',
  },
  {
    title: '描述',
    dataIndex: 'describe',
    // width: '30%',
    width: 375,
    key: 'describe',
  },
];

// 预估价格时效接口
const predictExpressOrder: DataType[] = [
  {
    key: 1,
    param: 'orderInfo',
    name: '下单信息',
    required: 'Y',
    type: 'object',
    demo: '',
    describe: '下单信息相关信息',
    children: [
      {
        key: 11,
        param: 'orderId',
        name: '订单号',
        required: 'Y',
        type: 'String',
        length: 32,
        demo: '',
        describe: '',
      },
      {
        key: 12,
        param: 'expressCode',
        name: '快递公司编码',
        required: 'Y',
        type: 'String',
        length: 16,
        demo: 'DBKD',
        describe: '快递公司的编码，一律用大写字母，见《快递公司编码》',
      },
      {
        key: 13,
        param: 'expressChannelCode',
        name: '快递渠道编码',
        required: 'N',
        type: 'String',
        length: 4,
        demo: '1',
        describe: '可传入与商务约定的快递渠道编码',
      },
      {
        key: 14,
        param: 'transportType',
        name: '运输方式/产品类型',
        required: 'Y',
        type: 'String',
        length: 16,
        demo: 'JZKH',
        describe: '快递公司的运输方式，见《快递产品类型编码》',
      },
      {
        key: 15,
        param: 'timeType',
        name: '时效类型',
        required: 'N',
        type: 'int',
        demo: '0',
        describe: '时效类型：0-预约单（默认），1-实时单',
      },
      {
        key: 16,
        param: 'sendStartTime',
        name: '预约取件开始时间',
        required: 'Y',
        type: 'String',
        length: 20,
        demo: '2023-04-26 11:00:00',
        describe: '',
      },
      {
        key: 17,
        param: 'sendEndTime',
        name: '预约取件结束时间',
        required: 'Y',
        type: 'String',
        length: 20,
        demo: '2023-04-26 13:00:00',
        describe: '',
      },
    ],
  },
  {
    key: 2,
    param: 'shippingInfo',
    name: '地址信息',
    required: 'Y',
    type: 'object',
    describe: '收寄件人相关信息',
    children: [
      {
        key: 21,
        param: 'sender',
        name: '寄件人信息',
        required: 'Y',
        type: 'object',
        demo: '',
        describe: '寄件人信息',
        children: [
          {
            key: 211,
            param: 'name',
            name: '寄件人姓名',
            required: 'Y',
            type: 'String',
            length: 20,
            demo: '张三',
            describe: '',
          },
          {
            key: 212,
            param: 'moblie',
            name: '寄件人手机号',
            required: 'Y',
            type: 'String',
            length: 20,
            demo: '13212341234',
            describe: '',
          },
          {
            key: 213,
            param: 'phone',
            name: '寄件人电话',
            required: 'N',
            type: 'String',
            length: 20,
            demo: '0571-12345678',
            describe: '',
          },
          {
            key: 214,
            param: 'province',
            name: '寄件省份',
            required: 'Y',
            type: 'String',
            length: 32,
            demo: '浙江省',
            describe: '',
          },
          {
            key: 215,
            param: 'city',
            name: '寄件城市',
            required: 'Y',
            type: 'String',
            length: 32,
            demo: '杭州市',
            describe: '',
          },
          {
            key: 216,
            param: 'county',
            name: '寄件区县',
            required: 'Y',
            type: 'String',
            length: 32,
            demo: '滨江区',
            describe: '',
          },
          {
            key: 217,
            param: 'address',
            name: '寄件详细地址',
            required: 'Y',
            type: 'String',
            length: 128,
            demo: '聚光中心D座',
            describe: '',
          },
        ],
      },
      {
        key: 22,
        param: 'receiver',
        name: '收件人信息',
        required: 'Y',
        type: 'object',
        demo: '',
        describe: '收件人信息',
        children: [
          {
            key: 221,
            param: 'name',
            name: '收件人姓名',
            required: 'Y',
            type: 'String',
            length: 20,
            demo: '张三',
            describe: '',
          },
          {
            key: 222,
            param: 'moblie',
            name: '收件人手机号',
            required: 'Y',
            type: 'String',
            length: 20,
            demo: '13212341234',
            describe: '',
          },
          {
            key: 223,
            param: 'phone',
            name: '收件人电话',
            required: 'N',
            type: 'String',
            length: 20,
            demo: '0571-12345678',
            describe: '',
          },
          {
            key: 224,
            param: 'province',
            name: '收件省份',
            required: 'Y',
            type: 'String',
            length: 32,
            demo: '浙江省',
            describe: '',
          },
          {
            key: 225,
            param: 'city',
            name: '收件城市',
            required: 'Y',
            type: 'String',
            length: 32,
            demo: '杭州市',
            describe: '',
          },
          {
            key: 226,
            param: 'county',
            name: '收件区县',
            required: 'Y',
            type: 'String',
            length: 32,
            demo: '滨江区',
            describe: '',
          },
          {
            key: 227,
            param: 'address',
            name: '收件详细地址',
            required: 'Y',
            type: 'String',
            length: 128,
            demo: '聚光中心D座',
            describe: '',
          },
        ],
      },
    ],
  },
  {
    key: 3,
    param: 'packageInfo',
    name: '物品类型',
    required: 'Y',
    type: 'object',
    demo: '',
    describe: '',
    children: [
      {
        key: 31,
        param: 'itemName',
        name: '物品名称',
        required: 'Y',
        type: 'String',
        length: 32,
        demo: '衣物',
        describe: '',
      },
      {
        key: 32,
        param: 'weight',
        name: '重量',
        required: 'Y',
        type: 'int',
        length: 10,
        demo: '1000',
        describe: '重量（克）',
      },
      {
        key: 33,
        param: 'volume',
        name: '体积',
        required: 'Y',
        type: 'int',
        length: 20,
        demo: '100000',
        describe: '体积（立方厘米）',
      },
      {
        key: 34,
        param: 'packageCount',
        name: '包裹数量',
        required: 'N',
        type: 'int',
        length: 4,
        demo: '1',
        describe: '包裹数量 默认1',
      },
    ],
  },
];

// 下单
const createExpressOrder: DataType[] = [
  {
    key: 1,
    param: 'orderInfo',
    name: '下单信息',
    required: 'Y',
    type: 'object',
    demo: '',
    describe: '下单信息相关信息',
    children: [
      {
        key: 11,
        param: 'orderId',
        name: '订单号',
        required: 'Y',
        type: 'String',
        length: 32,
        demo: '',
        describe: '',
      },
      {
        key: 12,
        param: 'orderOrigin',
        name: '下单来源',
        required: 'N',
        type: 'int',
        demo: '0',
        describe: '',
      },
      {
        key: 13,
        param: 'expressCode',
        name: '快递公司编码',
        required: 'Y',
        type: 'String',
        length: 16,
        demo: 'DBKD',
        describe: '快递公司的编码，一律用大写字母，见《快递公司编码》',
      },
      {
        key: 14,
        param: 'expressChannelCode',
        name: '快递渠道编码',
        required: 'N',
        type: 'String',
        length: 4,
        demo: '1',
        describe: '可传入与商务约定的快递渠道编码',
      },
      {
        key: 15,
        param: 'transportType',
        name: '运输方式/产品类型',
        required: 'Y',
        type: 'String',
        length: 16,
        demo: 'JZKH',
        describe: '快递公司的运输方式，见《快递产品类型编码》',
      },
      {
        key: 16,
        param: 'payType',
        name: '支付方式',
        required: 'N',
        type: 'int',
        demo: '0',
        describe: '0-寄付现结（线下支付给快递员）|1-到付（线下支付给快递员| 2-月结（总对总）',
      },
      {
        key: 17,
        param: 'timeType',
        name: '时效类型',
        required: 'N',
        type: 'int',
        demo: '0',
        describe: '时效类型：0-预约单（默认），1-实时单',
      },
      {
        key: 18,
        param: 'sendStartTime',
        name: '预约取件开始时间',
        required: 'Y',
        type: 'String',
        length: 20,
        demo: '2023-04-26 11:00:00',
        describe: '',
      },
      {
        key: 19,
        param: 'sendEndTime',
        name: '预约取件结束时间',
        required: 'Y',
        type: 'String',
        length: 20,
        demo: '2023-04-26 13:00:00',
        describe: '',
      },
    ],
  },
  {
    key: 2,
    param: 'shippingInfo',
    name: '地址信息',
    required: 'Y',
    type: 'object',
    describe: '收寄件人相关信息',
    children: [
      {
        key: 21,
        param: 'sender',
        name: '寄件人信息',
        required: 'Y',
        type: 'object',
        demo: '',
        describe: '寄件人信息',
        children: [
          {
            key: 211,
            param: 'name',
            name: '寄件人姓名',
            required: 'Y',
            type: 'String',
            length: 20,
            demo: '张三',
            describe: '',
          },
          {
            key: 212,
            param: 'moblie',
            name: '寄件人手机号',
            required: 'Y',
            type: 'String',
            length: 20,
            demo: '13212341234',
            describe: '',
          },
          {
            key: 213,
            param: 'phone',
            name: '寄件人电话',
            required: 'N',
            type: 'String',
            length: 20,
            demo: '0571-12345678',
            describe: '',
          },
          {
            key: 214,
            param: 'province',
            name: '寄件省份',
            required: 'Y',
            type: 'String',
            length: 32,
            demo: '浙江省',
            describe: '',
          },
          {
            key: 215,
            param: 'city',
            name: '寄件城市',
            required: 'Y',
            type: 'String',
            length: 32,
            demo: '杭州市',
            describe: '',
          },
          {
            key: 216,
            param: 'county',
            name: '寄件区县',
            required: 'Y',
            type: 'String',
            length: 32,
            demo: '滨江区',
            describe: '',
          },
          {
            key: 217,
            param: 'address',
            name: '寄件详细地址',
            required: 'Y',
            type: 'String',
            length: 128,
            demo: '聚光中心D座',
            describe: '',
          },
        ],
      },
      {
        key: 22,
        param: 'receiver',
        name: '收件人信息',
        required: 'Y',
        type: 'object',
        demo: '',
        describe: '收件人信息',
        children: [
          {
            key: 221,
            param: 'name',
            name: '收件人姓名',
            required: 'Y',
            type: 'String',
            length: 20,
            demo: '张三',
            describe: '',
          },
          {
            key: 222,
            param: 'moblie',
            name: '收件人手机号',
            required: 'Y',
            type: 'String',
            length: 20,
            demo: '13212341234',
            describe: '',
          },
          {
            key: 223,
            param: 'phone',
            name: '收件人电话',
            required: 'N',
            type: 'String',
            length: 20,
            demo: '0571-12345678',
            describe: '',
          },
          {
            key: 224,
            param: 'province',
            name: '收件省份',
            required: 'Y',
            type: 'String',
            length: 32,
            demo: '浙江省',
            describe: '',
          },
          {
            key: 225,
            param: 'city',
            name: '收件城市',
            required: 'Y',
            type: 'String',
            length: 32,
            demo: '杭州市',
            describe: '',
          },
          {
            key: 226,
            param: 'county',
            name: '收件区县',
            required: 'Y',
            type: 'String',
            length: 32,
            demo: '滨江区',
            describe: '',
          },
          {
            key: 227,
            param: 'address',
            name: '收件详细地址',
            required: 'Y',
            type: 'String',
            length: 128,
            demo: '聚光中心D座',
            describe: '',
          },
        ],
      },
    ],
  },
  {
    key: 3,
    param: 'packageInfo',
    name: '物品类型',
    required: 'Y',
    type: 'object',
    demo: '',
    describe: '',
    children: [
      {
        key: 31,
        param: 'itemName',
        name: '物品名称',
        required: 'Y',
        type: 'String',
        length: 32,
        demo: '衣物',
        describe: '',
      },
      {
        key: 32,
        param: 'weight',
        name: '重量',
        required: 'Y',
        type: 'int',
        length: 10,
        demo: '1000',
        describe: '重量（克）',
      },
      {
        key: 33,
        param: 'volume',
        name: '体积',
        required: 'Y',
        type: 'int',
        length: 20,
        demo: '100000',
        describe: '体积（立方厘米）',
      },
      {
        key: 34,
        param: 'packageCount',
        name: '包裹数量',
        required: 'N',
        type: 'int',
        length: 4,
        demo: '1',
        describe: '包裹数量 默认1',
      },
      {
        key: 35,
        param: 'remake',
        name: '备注',
        required: 'Y',
        type: 'String',
        length: 100,
        demo: '加急哦',
        describe: '',
      },
    ],
  },
  {
    key: 4,
    param: 'addServices',
    name: '增值服务',
    required: 'N',
    type: 'object',
    demo: '',
    describe: '',
    children: [
      {
        key: 41,
        param: 'insuranceValue',
        name: '物品价值',
        required: 'N',
        type: 'int',
        demo: '3000',
        describe: '目前仅支持德邦、京东，其余快递无法保价；如为空，则下单时默认为0，单位：分',
      },
    ],
  },
  {
    key: 5,
    param: 'orderExtendFields',
    name: '扩展字段',
    required: 'N',
    type: 'object',
    demo: '',
    describe: '扩展字段',
    children: [
      {
        key: 51,
        param: 'pickupCode',
        name: '取件码',
        required: 'N',
        type: 'String',
        length: 1,
        demo: '0',
        describe: '1-自定义取件码；2-快递公司取件码，不需要取件码不要传入，目前仅德邦支持',
      },
      {
        key: 52,
        param: 'codeKey',
        name: '自定义取件码',
        required: 'N',
        type: 'String',
        length: 6,
        demo: '123456',
        describe: '自定义码，仅支持4位、6位阿拉伯数字，目前仅德邦支持',
      },
      {
        key: 52,
        param: 'itemVersion',
        name: '版本',
        required: 'N',
        type: 'int',
        demo: '3',
        describe: '菜鸟必填，通过预查询返回填入',
      },
    ],
  },
];

// 取消订单
const cancelExpressOrder: DataType[] = [
  {
    key: 1,
    param: 'orderInfo',
    name: '订单信息',
    required: 'Y',
    type: 'object',
    demo: '',
    describe: '',
    children: [
      {
        key: 11,
        param: 'orderId',
        name: '订单号',
        required: 'Y',
        type: 'String',
        length: 32,
        demo: '',
        describe: '',
      },
    ],
  },
  {
    key: 2,
    param: 'reasonCode',
    name: '取消原因编码',
    required: 'Y',
    type: 'init',
    demo: '6',
    describe:
      '0-暂时不想寄快递了  1-运费过高，更换寄快递方式  2-信息填写错误  3-快递员原因  4-无法送达目的地  5-下错单了，需要重新下单  6-其它',
  },
  {
    key: 3,
    param: 'reasonDesc',
    name: '取消原因',
    required: 'N',
    type: 'String',
    length: 50,
    demo: '计划有变，暂不寄件',
    describe: 'reasonCode为6时必填入，最多50字  0-5默认传对应枚举值的原因，不可更改',
  },
];

// 2-5 物流轨迹查询接口
const searchExpressOrderLogistics: DataType[] = [
  {
    key: 1,
    param: 'orderInfo',
    name: '订单信息',
    required: 'Y',
    type: 'object',
    demo: '',
    describe: '',
    children: [
      {
        key: 11,
        param: 'orderId',
        name: '订单号',
        required: 'Y',
        type: 'String',
        length: 32,
        demo: '',
        describe: '',
      },
    ],
  },
];

// 2-5 物流轨迹查询接口 - 返回参数
const searchExpressOrderLogistics_return: DataType[] = [
  {
    key: 1,
    param: 'orderId',
    name: '订单编号',
    required: 'Y',
    type: 'String',
    length: 32,
    demo: '',
    describe: '',
  },
  {
    key: 2,
    param: 'companyCode',
    name: '快递编码',
    required: 'Y',
    type: 'String',
    length: 12,
    demo: '',
    describe: '',
  },
  {
    key: 3,
    param: 'companyName',
    name: '快递名称',
    required: 'Y',
    type: 'String',
    length: 20,
    demo: '',
    describe: '',
  },
  {
    key: 4,
    param: 'waybillCode',
    name: '运单号',
    required: 'Y',
    type: 'String',
    length: 32,
    demo: '',
    describe: '',
  },
  {
    key: 5,
    param: 'trackList',
    name: '物流列表',
    required: 'Y',
    type: 'array',
    demo: '',
    describe: '',
    children: [
      {
        key: 51,
        param: 'traceTime',
        name: '物流时间',
        required: 'Y',
        type: 'String',
        length: 20,
        demo: '',
        describe: '',
      },
      {
        key: 52,
        param: 'traceStatus',
        name: '物流状态',
        required: 'Y',
        type: 'String',
        length: 128,
        demo: '',
        describe: '',
      },
    ],
  },
];

// 2-6 盲区校验（是否可达）接口
const checkAddress: DataType[] = [
  {
    key: 1,
    param: 'expressCode',
    name: '快递公司编码',
    required: 'Y',
    type: 'String',
    length: 20,
    demo: 'DBKD',
    describe: '快递公司的编码，一律用大写字母，见《快递公司编码》',
  },
  {
    key: 2,
    param: 'expressChannelCode',
    name: '快递渠道编码',
    required: 'N',
    type: 'String',
    length: 20,
    demo: '1',
    describe: '非必填；可传入与业务约定的快递渠道编码',
  },
  {
    key: 3,
    param: 'transportType',
    name: '运输方式/产品类型',
    required: 'Y',
    type: 'String',
    length: 20,
    demo: 'JZKH',
    describe: '快递公司的运输方式，见《快递产品类型编码》',
  },
  {
    key: 4,
    param: 'receiver',
    name: '地址信息',
    required: 'Y',
    type: 'array',
    demo: '',
    describe: '地址信息数组，最多填入10组地址',
    children: [
      {
        key: 41,
        param: 'province',
        name: '省份',
        required: 'Y',
        type: 'String',
        length: 32,
        demo: '浙江省',
        describe: '',
      },
      {
        key: 42,
        param: 'city',
        name: '城市',
        required: 'Y',
        type: 'String',
        length: 32,
        demo: '杭州市',
        describe: '',
      },
      {
        key: 43,
        param: 'county',
        name: '区县',
        required: 'Y',
        type: 'String',
        length: 32,
        demo: '滨江区',
        describe: '',
      },
      {
        key: 44,
        param: 'address',
        name: '详细地址',
        required: 'Y',
        type: 'String',
        length: 128,
        demo: '聚光中心D座',
        describe: '',
      },
    ],
  },
];

// 2-6 盲区校验（是否可达）接口 - 返回参数
const checkAddress_return: DataType[] = [
  {
    key: 1,
    param: 'receiver',
    name: '地址信息',
    required: 'Y',
    type: 'object',
    demo: '',
    describe: '',
    children: [
      {
        key: 11,
        param: 'province',
        name: '省份',
        required: 'Y',
        type: 'String',
        length: 32,
        demo: '浙江省',
        describe: '',
      },
      {
        key: 12,
        param: 'city',
        name: '城市',
        required: 'Y',
        type: 'String',
        length: 32,
        demo: '杭州市',
        describe: '',
      },
      {
        key: 13,
        param: 'county',
        name: '区县',
        required: 'Y',
        type: 'String',
        length: 32,
        demo: '滨江区',
        describe: '',
      },
      {
        key: 14,
        param: 'address',
        name: '详细地址',
        required: 'Y',
        type: 'String',
        length: 128,
        demo: '聚光中心D座',
        describe: '',
      },
    ],
  },
  {
    key: 2,
    param: 'reachResult',
    name: '可达结果',
    required: 'Y',
    type: 'boolean',
    demo: 'true',
    describe: '是否可达',
  },
  {
    key: 3,
    param: 'reason',
    name: '原因',
    required: 'N',
    type: 'String',
    length: 128,
    demo: '',
    describe: '不可达原因',
  },
];

// 2-7 订单查询接口
const queryOrder: DataType[] = [
  {
    key: 1,
    param: 'orderInfo',
    name: '订单信息',
    required: 'Y',
    type: 'object',
    demo: '',
    describe: '',
    children: [
      {
        key: 11,
        param: 'orderId',
        name: '订单号',
        required: 'Y',
        type: 'String',
        length: 32,
        demo: '',
        describe: '',
      },
    ],
  },
];

// 2-7 订单查询接口 - 返回参数
const queryOrder_return: DataType[] = [
  {
    key: 1,
    param: 'orderStatus',
    name: '订单状态',
    required: 'Y',
    type: 'int',
    demo: '0',
    describe: '0-正常 1-取消',
  },
  {
    key: 2,
    param: 'settleStatus',
    name: '订单结算状态',
    required: 'Y',
    type: 'int',
    demo: '',
    describe: '1-已结算  0-待结算',
  },
  {
    key: 3,
    param: 'logisticsStatus',
    name: '订单物流状态',
    required: 'Y',
    type: 'int',
    demo: '',
    describe:
      '0-已创建,无记录 7-已揽件 8-运输中 1-派送中 2-已签收  6-疑难件 9-已送达（配送） 10-已分配快递员待揽收（快递下单）',
  },
  {
    key: 4,
    param: 'priceInfo',
    name: '费用信息',
    required: 'N',
    type: 'Object',
    demo: '',
    describe: '',
    children: [
      {
        key: 41,
        param: 'feeList',
        name: '费用明细',
        required: 'N',
        type: 'Object',
        demo: '',
        describe: '',
        children: [
          {
            key: 411,
            param: 'code',
            name: '费用编码',
            required: 'Y',
            type: 'String',
            length: 16,
            demo: 'base',
            describe: '',
          },
          {
            key: 412,
            param: 'name',
            name: '费用名称',
            required: 'Y',
            type: 'String',
            length: 32,
            demo: '基础运费',
            describe: '',
          },
          {
            key: 413,
            param: 'value',
            name: '金额',
            required: 'Y',
            type: 'int',
            demo: '1000',
            describe: '单位（分）',
          },
        ],
      },
      {
        key: 42,
        param: 'packageWeight',
        name: '包裹重量',
        required: 'N',
        type: 'int',
        demo: '1000',
        describe: '单位（克）',
      },
      {
        key: 43,
        param: 'volume',
        name: '体积',
        required: 'N',
        type: 'long',
        demo: '100000',
        describe: '单位（体积）',
      },
      {
        key: 44,
        param: 'calculateWeight',
        name: '计费重量',
        required: 'N',
        type: 'int',
        demo: '1000',
        describe: '单位（克），结算使用的重量',
      },
    ],
  },
];

const dataSourceSet: DataType[][] = [
  predictExpressOrder,
  createExpressOrder,
  cancelExpressOrder,
  searchExpressOrderLogistics,
  searchExpressOrderLogistics_return,
  checkAddress,
  checkAddress_return,
  queryOrder,
  queryOrder_return,
];
console.log(dataSourceSet);
const APITable: React.FC<{
  idx: number;
}> = ({ idx = 0 }) => {
  console.log(dataSourceSet[idx], idx);
  return (
    <>
      <Table
        columns={columns}
        // expandable={{ defaultExpandAllRows: true }}
        dataSource={dataSourceSet[idx]}
        pagination={false}
      />
    </>
  );
};

export default APITable;
