const map = {
  xx: {
    data: '',
    c: 'xx',
  },
  yy: {
    data: [
      {
        key: 1,
        param: 'orderInfo',
        name: '下单信息',
        required: 'Y',
        type: 'object',
        demo: '',
        describe: '下单信息相关信息',
        children: [
          {
            key: 11,
            param: 'orderId',
            name: '订单号',
            required: 'Y',
            type: 'String',
            length: 32,
            demo: '',
            describe: '',
          },
          {
            key: 12,
            param: 'expressCode',
            name: '快递公司编码',
            required: 'Y',
            type: 'String',
            length: 16,
            demo: 'DBKD',
            describe: '快递公司的编码，一律用大写字母，见《快递公司编码》',
          },
          {
            key: 13,
            param: 'expressChannelCode',
            name: '快递渠道编码',
            required: 'N',
            type: 'String',
            length: 4,
            demo: '1',
            describe: '可传入与商务约定的快递渠道编码',
          },
          {
            key: 14,
            param: 'transportType',
            name: '运输方式/产品类型',
            required: 'Y',
            type: 'String',
            length: 16,
            demo: 'JZKH',
            describe: '快递公司的运输方式，见《快递产品类型编码》',
          },
          {
            key: 15,
            param: 'timeType',
            name: '时效类型',
            required: 'N',
            type: 'int',
            demo: '0',
            describe: '时效类型：0-预约单（默认），1-实时单',
          },
          {
            key: 16,
            param: 'sendStartTime',
            name: '预约取件开始时间',
            required: 'Y',
            type: 'String',
            length: 20,
            demo: '2023-04-26 11:00:00',
            describe: '',
          },
          {
            key: 17,
            param: 'sendEndTime',
            name: '预约取件结束时间',
            required: 'Y',
            type: 'String',
            length: 20,
            demo: '2023-04-26 13:00:00',
            describe: '',
          },
        ],
      },
      {
        key: 2,
        param: 'shippingInfo',
        name: '地址信息',
        required: 'Y',
        type: 'object',
        describe: '收寄件人相关信息',
        children: [
          {
            key: 21,
            param: 'sender',
            name: '寄件人信息',
            required: 'Y',
            type: 'object',
            demo: '',
            describe: '寄件人信息',
            children: [
              {
                key: 211,
                param: 'name',
                name: '寄件人姓名',
                required: 'Y',
                type: 'String',
                length: 20,
                demo: '张三',
                describe: '',
              },
              {
                key: 212,
                param: 'moblie',
                name: '寄件人手机号',
                required: 'Y',
                type: 'String',
                length: 20,
                demo: '13212341234',
                describe: '',
              },
              {
                key: 213,
                param: 'phone',
                name: '寄件人电话',
                required: 'N',
                type: 'String',
                length: 20,
                demo: '0571-12345678',
                describe: '',
              },
              {
                key: 214,
                param: 'province',
                name: '寄件省份',
                required: 'Y',
                type: 'String',
                length: 32,
                demo: '浙江省',
                describe: '',
              },
              {
                key: 215,
                param: 'city',
                name: '寄件城市',
                required: 'Y',
                type: 'String',
                length: 32,
                demo: '杭州市',
                describe: '',
              },
              {
                key: 216,
                param: 'county',
                name: '寄件区县',
                required: 'Y',
                type: 'String',
                length: 32,
                demo: '滨江区',
                describe: '',
              },
              {
                key: 217,
                param: 'address',
                name: '寄件详细地址',
                required: 'Y',
                type: 'String',
                length: 128,
                demo: '聚光中心D座',
                describe: '',
              },
            ],
          },
          {
            key: 22,
            param: 'receiver',
            name: '收件人信息',
            required: 'Y',
            type: 'object',
            demo: '',
            describe: '收件人信息',
            children: [
              {
                key: 221,
                param: 'name',
                name: '收件人姓名',
                required: 'Y',
                type: 'String',
                length: 20,
                demo: '张三',
                describe: '',
              },
              {
                key: 222,
                param: 'moblie',
                name: '收件人手机号',
                required: 'Y',
                type: 'String',
                length: 20,
                demo: '13212341234',
                describe: '',
              },
              {
                key: 223,
                param: 'phone',
                name: '收件人电话',
                required: 'N',
                type: 'String',
                length: 20,
                demo: '0571-12345678',
                describe: '',
              },
              {
                key: 224,
                param: 'province',
                name: '收件省份',
                required: 'Y',
                type: 'String',
                length: 32,
                demo: '浙江省',
                describe: '',
              },
              {
                key: 225,
                param: 'city',
                name: '收件城市',
                required: 'Y',
                type: 'String',
                length: 32,
                demo: '杭州市',
                describe: '',
              },
              {
                key: 226,
                param: 'county',
                name: '收件区县',
                required: 'Y',
                type: 'String',
                length: 32,
                demo: '滨江区',
                describe: '',
              },
              {
                key: 227,
                param: 'address',
                name: '收件详细地址',
                required: 'Y',
                type: 'String',
                length: 128,
                demo: '聚光中心D座',
                describe: '',
              },
            ],
          },
        ],
      },
      {
        key: 3,
        param: 'packageInfo',
        name: '物品类型',
        required: 'Y',
        type: 'object',
        demo: '',
        describe: '',
        children: [
          {
            key: 31,
            param: 'itemName',
            name: '物品名称',
            required: 'Y',
            type: 'String',
            length: 32,
            demo: '衣物',
            describe: '',
          },
          {
            key: 32,
            param: 'weight',
            name: '重量',
            required: 'Y',
            type: 'int',
            length: 10,
            demo: '1000',
            describe: '重量（克）',
          },
          {
            key: 33,
            param: 'volume',
            name: '体积',
            required: 'Y',
            type: 'int',
            length: 20,
            demo: '100000',
            describe: '体积（立方厘米）',
          },
          {
            key: 34,
            param: 'packageCount',
            name: '包裹数量',
            required: 'N',
            type: 'int',
            length: 4,
            demo: '1',
            describe: '包裹数量 默认1',
          },
        ],
      },
    ],
    c: 'xxx',
  },
};
